config/routes.rb
Rails.application.routes.draw do
  root to: "pages#home"

  get "videos", to: "pages#videos"
  get "photos", to: "pages#photos"
  get "photos/ardaarman", to: "pages#ardaarman"
  get "photos/brandon", to: "pages#brandon"
  get "photos/nyc", to: "pages#nyc"
  get "photos/salomon", to: "pages#salomon"





  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def videos
  end

  def photos
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AysanWebsite</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/ardaarman.html.erb
<a href="<%= root_path %>" class="back-btn">home</a>

<div class="photos-div">
    <div class="text-div">
        <ul>
            <li><a href="<%= photos_ardaarman_path %>" style="color: blue !important;">01 Arda Arman</a></li>
            <li><a href="<%= photos_brandon_path %>">02 Brandon</a></li>
            <li><a href="<%= photos_nyc_path %>">03 NYC</a></li>
            <li><a href="<%= photos_salomon_path %>">04 Salomon</a></li>
        </ul>
    </div>
    <div class="image-div">
        <%= image_tag ("ardaarman/a1.jpg"), :class => "image"%>
        <div class="project-desc">
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean finibus augue vel pretium aliquet. Nullam ipsum sem, maximus eget tristique et, maximus ac odio. Nam tempus scelerisque tempus. Maecenas dapibus et enim sit amet pulvinar. Ut non dolor eu lacus sodales iaculis in sit amet nisi. Donec blandit scelerisque sem. Morbi semper ultricies ligula ut sollicitudin. Cras posuere blandit suscipit</p>
        </div>
        <%= image_tag ("ardaarman/a2.jpg"), :class => "image"%>
        <%= image_tag ("ardaarman/a3.jpg"), :class => "image"%>
        <%= image_tag ("ardaarman/a4.jpg"), :class => "image"%>
        <%= image_tag ("ardaarman/a5.jpg"), :class => "image"%>
        <%= image_tag ("ardaarman/a6.jpg"), :class => "image"%>
        <%= image_tag ("ardaarman/a7.jpg"), :class => "image"%>
        <%= image_tag ("ardaarman/a8.jpg"), :class => "image"%>
        <%= image_tag ("ardaarman/a9.jpg"), :class => "image"%>
    </div>
</div>

app/views/pages/brandon.html.erb
<a href="<%= root_path %>" class="back-btn">home</a>

<div class="photos-div">
    <div class="text-div">
        <ul>
            <li><a href="<%= photos_ardaarman_path %>">01 New York Project</a></li>
            <li><a href="<%= photos_brandon_path %>" style="color: blue !important;">02 Brandon</a></li>
            <li><a href="<%= photos_nyc_path %>">03 NYC</a></li>
            <li><a href="<%= photos_salomon_path %>">04 Salomon</a></li>
        </ul>
    </div>
    <div class="image-div">
        <%= image_tag ("brandon/b1.jpg"), :class => "image"%>
        <div class="project-desc">
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean finibus augue vel pretium aliquet. Nullam ipsum sem, maximus eget tristique et, maximus ac odio. Nam tempus scelerisque tempus. Maecenas dapibus et enim sit amet pulvinar. Ut non dolor eu lacus sodales iaculis in sit amet nisi. Donec blandit scelerisque sem. Morbi semper ultricies ligula ut sollicitudin. Cras posuere blandit suscipit</p>
        </div>
        <%= image_tag ("brandon/b2.jpg"), :class => "image"%>
        <%= image_tag ("brandon/b3.jpg"), :class => "image"%>
        <%= image_tag ("brandon/b4.jpg"), :class => "image"%>
        <%= image_tag ("brandon/b5.jpg"), :class => "image"%>
    </div>
</div>

app/views/pages/home.html.erb
<div id="home-div">
    <div id="images-div" class="slideshow">
        <%= image_tag ("ardaarman/a1.jpg"), :class => "image", :style => "display: block"%>
        <%= image_tag ("brandon/b1.jpg"), :class => "image", :style => "display: none" %>
        <%= image_tag ("nyc/ny1.jpg"), :class => "image", :style => "display: none" %>
        <%= image_tag ("salomon/s1.jpg"), :class => "image", :style => "display: none" %>
    </div>
    <div id="buttons-div">
        <div id="photos-div" class="div-one-part"><a href="<%= photos_path %>">photos</a></div>
        <div id="videos-div" class="div-one-part"><a href="<%= videos_path %>">videos</a></div>
    </div>
</div>

<script>
// Get the slideshow container
  var slideshow = document.querySelector('.slideshow');

  // Get the images
  var images = slideshow.querySelectorAll('img');

  // Set the index to the first image
  var index = 0;

  // Set the interval for the slideshow
  var interval = setInterval(showNextImage, 3000);

  function showNextImage() {
      // Hide the current image
      images[index].style.display = 'none';

      // Increment the index
      index = (index + 1) % images.length;

      // Show the next image
      images[index].style.display = 'block';
  }
</script>

<div id="footer-div">
    <p><a href = "mailto: metin.lamby@outlook.com">contact</a> | <a href="https://www.instagram.com/aysanlamby/?hl=en">instagram</a></p>
</div>

app/views/pages/nyc.html.erb
<a href="<%= root_path %>" class="back-btn">home</a>

<div class="photos-div">
    <div class="text-div">
        <ul>
            <li><a href="<%= photos_ardaarman_path %>">01 New York Project</a></li>
            <li><a href="<%= photos_brandon_path %>">02 Brandon</a></li>
            <li><a href="<%= photos_nyc_path %>" style="color: blue !important;">03 NYC</a></li>
            <li><a href="<%= photos_salomon_path %>">04 Salomon</a></li>
        </ul>
    </div>
    <div class="image-div">
        <%= image_tag ("nyc/ny1.jpg"), :class => "image"%>
        <div class="project-desc">
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean finibus augue vel pretium aliquet. Nullam ipsum sem, maximus eget tristique et, maximus ac odio. Nam tempus scelerisque tempus. Maecenas dapibus et enim sit amet pulvinar. Ut non dolor eu lacus sodales iaculis in sit amet nisi. Donec blandit scelerisque sem. Morbi semper ultricies ligula ut sollicitudin. Cras posuere blandit suscipit</p>
        </div>
        <%= image_tag ("nyc/ny2.jpg"), :class => "image"%>
        <%= image_tag ("nyc/ny3.jpg"), :class => "image"%>
        <%= image_tag ("nyc/ny4.jpg"), :class => "image"%>
        <%= image_tag ("nyc/ny5.jpg"), :class => "image"%>
        <%= image_tag ("nyc/ny6.jpg"), :class => "image"%>
        <%= image_tag ("nyc/ny7.jpg"), :class => "image"%>
        <%= image_tag ("nyc/ny8.jpg"), :class => "image"%>
    </div>
</div>

app/views/pages/photos.html.erb
<a href="<%= root_path %>" class="back-btn">home</a>
<div class="photos-div" data-controller="images" data-action="images#changeImageList">
    <div class="text-div">
        <ul>
            <li><a href="<%= photos_ardaarman_path %>">01 Arda Arman</a></li>
            <li><a href="<%= photos_brandon_path %>">02 Brandon</a></li>
            <li><a href="<%= photos_nyc_path %>">03 NYC</a></li>
            <li><a href="<%= photos_salomon_path %>">04 Salomon</a></li>
        </ul>
    </div>
    <div class="image-div">
        <%= image_tag ("ardaarman/a1.jpg"), :class => "image"%>
        <%= image_tag ("brandon/b1.jpg"), :class => "image"%>
        <%= image_tag ("nyc/ny1.jpg"), :class => "image"%>
        <%= image_tag ("salomon/s1.jpg"), :class => "image"%>
    </div>
</div>

app/views/pages/salomon.html.erb
<a href="<%= root_path %>" class="back-btn">home</a>

<div class="photos-div">
    <div class="text-div">
        <ul>
            <li><a href="<%= photos_ardaarman_path %>">01 New York Project</a></li>
            <li><a href="<%= photos_brandon_path %>">02 Brandon</a></li>
            <li><a href="<%= photos_nyc_path %>">03 NYC</a></li>
            <li><a href="<%= photos_salomon_path %>" style="color: blue !important;">04 Salomon</a></li>
        </ul>
    </div>
    <div class="image-div">
        <%= image_tag ("salomon/s1.jpg"), :class => "image"%>
        <div class="project-desc">
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean finibus augue vel pretium aliquet. Nullam ipsum sem, maximus eget tristique et, maximus ac odio. Nam tempus scelerisque tempus. Maecenas dapibus et enim sit amet pulvinar. Ut non dolor eu lacus sodales iaculis in sit amet nisi. Donec blandit scelerisque sem. Morbi semper ultricies ligula ut sollicitudin. Cras posuere blandit suscipit</p>
        </div>
        <%= image_tag ("salomon/s2.jpg"), :class => "image"%>
        <%= image_tag ("salomon/s3.jpg"), :class => "image"%>
        <%= image_tag ("salomon/s4.jpg"), :class => "image"%>
        <%= image_tag ("salomon/s5.jpg"), :class => "image"%>
        <%= image_tag ("salomon/s6.jpg"), :class => "image"%>
        <%= image_tag ("salomon/s7.jpg"), :class => "image"%>
        <%= image_tag ("salomon/s8.jpg"), :class => "image"%>
    </div>
</div>

app/views/pages/videos.html.erb
<a href="<%= root_path %>" class="back-btn">home</a>